- findbugs-exclude.xml
- pom.xml
- src/main/java/hudson/plugins/active_directory/AbstractActiveDirectoryAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUserDetail.java
- src/main/java/hudson/plugins/active_directory/MultiCauseBadCredentialsException.java
- src/main/java/hudson/plugins/active_directory/MultiCauseUserMayOrMayNotExistException.java
- src/main/java/hudson/plugins/active_directory/MultiCauseUserNotFoundException.java
And configuration for xml output so Jenkins can pick it up
@reviewbybees
> Fix findbugs issues

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
`com.sun.jndi.ldap.Connection.readReply()` apparently times out after 15secs with an error like this:
```
Caused by: javax.naming.NamingException: LDAP response read timed out, timeout used:-1ms.; remaining name 'DC=example,DC=com'
at com.sun.jndi.ldap.Connection.readReply(Unknown Source)
at com.sun.jndi.ldap.LdapClient.getSearchReply(Unknown Source)
at com.sun.jndi.ldap.LdapClient.search(Unknown Source)
at com.sun.jndi.ldap.LdapCtx.doSearch(Unknown Source)
at com.sun.jndi.ldap.LdapCtx.searchAux(Unknown Source)
at com.sun.jndi.ldap.LdapCtx.c_search(Unknown Source)
at com.sun.jndi.ldap.LdapCtx.c_search(Unknown Source)
at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(Unknown Source)
at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(Unknown Source)
at …
```
> [FIXED JENKINS-28857] Catch the case in which LDAP times out after some seconds

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/LDAPSearchBuilder.java
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/help-bindName.html
We need to escape the special characters per:
* http://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx
@reviewbybees CC @jtnord
> [FIXED JENKINS 16257] Active Directory Plugin - Credential exception tying to authenticate with special characters like / or #

- pom.xml
@reviewbybees  CC @oleg-nenashev
> Update maven release plugin

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
```
if (!found || duration >= 10) {
LOGGER.warning(String.format("AD chain lookup is taking too long (%dms). Falling back to recursive lookup", duration));
groupLookupStrategy = GroupLookupStrategy.RECURSIVE;
continue;
}
```
This logic smells wrong. We could have found the responses - just taken more than 10 seconds.
https://issues.jenkins-ci.org/browse/JENKINS-33260
@reviewbybees CC @jtnord
> [FIXED JENKINS-33260] Change the logic when resolving groups

- pom.xml
> Correctly manage maven-release-plugin on pom.xml

- pom.xml
> Add fbelzunc as developer of the Active Directory plugin

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
The problem is that there was a recursive cache and it is not necessary since when accessing through token you will end up calling the corresponded method which will cache if necessary.
https://issues.jenkins-ci.org/browse/JENKINS-34426
```
hudson.plugins.active_directory.CacheAuthenticationException: Authentication failed caching user <here the user/group>; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recursive load
at hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:194)
at hudson.plugins.active_directory.AbstractActiveDirectoryAuthenticationProvider.loadUserByUsername(AbstractActiveDirectoryAuthenticationProvider.java:54)
at …
```
> [FIXED JENKINS-34426] LDAP users and groups cannot be verified anymore

- .gitignore
- pom.xml
- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUserDetail.java
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/config.jelly
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
- src/main/resources/index.jelly
> [JENKINS-34508] Migrate to 2.7 parent pom

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
https://issues.jenkins-ci.org/browse/JENKINS-35031
@reviewbybees CC @jtnord @andresrc
> [JENKINS-35031] Not check password if it is NO_AUTHENTICATION

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
https://issues.jenkins-ci.org/browse/JENKINS-37582
@reviewbybees CC @andresrc @jtnord
> [JENKINS-37582] Not return null inside the cache

- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/EnvironmentProperty/config.jelly
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/help-extraEnvVars.html
Set-up Default  ldap timeouts and allow their configuration through the UI
This PR address:
* https://issues.jenkins-ci.org/browse/JENKINS-36041
@reviewbybees CC @jtnord @andresrc
> [FIXED JENKINS-36041] Default  ldap timeouts and allow their configuration through the UI

- pom.xml
- src/main/resources/index.jelly
[JENKINS-42245](https://issues.jenkins-ci.org/browse/JENKINS-42245)
@reviewbybees @kohsuke @fbelzunc
> [FIXED JENKINS-42245] Add description according to Wiki

- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/help-startTls.html
https://issues.jenkins-ci.org/browse/JENKINS-42641
> [FIXED JENKINS-42641] Configure startTls on the UI

- pom.xml
- src/main/java/hudson/plugins/active_directory/GroupLookupStrategy.java
- src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/Dockerfile
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/custom.sh
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/init.sh
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/kdb5_util_create.expect
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/krb5.conf
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/named.conf.options
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/sssd.conf
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/supervisord.conf
Submit this PR to get help from colleagues.
> Add Docker integration tests

- src/main/webapp/help/domain-name-unix.html
https://issues.jenkins-ci.org/browse/JENKINS-46228
> [FIXED JENKINS-46228] Correct in the help button how to add multiple-domains

- Jenkinsfile
In order to be able to create integration tests using the DNS of the AD controller, I am creating a build container and modifying the Jenkinsfile in order to use it.
> Use a docker build container

- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryDomain.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/Dockerfile
- src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/init.sh
[JENKINS-36148](https://issues.jenkins-ci.org/browse/JENKINS-36148)
> [FIXED JENKINS-36148] The test ignores the custom server if specified

- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/config.jelly
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configCache.jelly
- src/test/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest.java
https://issues.jenkins-ci.org/browse/JENKINS-46884
> [FIXED JENKINS-46884] Make cache available for native authentication

- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
Add getCustomDomain() to improve JCASC compatibility.
> [FIXED JENKINS-53576] - Improve JCASC compatibility

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryDomain.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryStatus.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUserDetail.java
- src/main/java/hudson/plugins/active_directory/LDAPSearchBuilder.java
- src/main/java/hudson/plugins/active_directory/TrustAllSocketFactory.java
- src/main/resources/hudson/plugins/active_directory/ActiveDirectory.groovy
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/help-removeIrrelevantGroups.html
- src/main/resources/hudson/plugins/active_directory/Messages.properties
- src/test/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest.java
- src/test/java/hudson/plugins/active_directory/RemoveIrrelevantGroupsTest.java
- src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
I suggest to review this pull request commit by commit as each one covers a different aspect.
> Code cleanup

- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
In case the `StartTls` connection does not work correctly, the plugin should automatically fall back into the plain-text communication. The problem is that when `StartTls` fails with an `Exception`, then the fallback does not work in ALL cases.
I was able to reproduce this issue launching a CertPathValidatorException. In this case, it is not even a possibility to just close the `StartTls` connection and to re-create the full `LdapContext` is needed.
```
2019-04-30 15:44:58.322+0000 [id=48]	FINE	h.p.a.ActiveDirectorySecurityRealm$DescriptorImpl#bind: Failed to start TLS. Authentication will be done via plain-text LDAP
java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: 1.2.840.113549.1.1.10
at …
```
> [JENKINS-44787] Some Exceptions launched by startTLS might break the log-in

- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
[JENKINS-63737](https://issues.jenkins-ci.org/browse/JENKINS-63737): performance regression in #102.
> [JENKINS-63737] Cache AbstractActiveDirectoryAuthenticationProvider

- README.md
https://issues.jenkins-ci.org/browse/JENKINS-63664
> [JENKINS-63664] Update docs to better explain how to user the internal fall-back user and its limitations

- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/config.jelly
- src/main/resources/lib/active_directory/blockWrapper.jelly
Tested on my instance, this change fixed all issues I was seeing with "Configure Global Security"
> JENKINS-64130 JENKINS-64255 Tables to divs compat

- .github/dependabot.yml
This will help to keep the dependencies of the project up-to-date.
> Setup automatic dependency updates

- pom.xml
- src/test/java/hudson/plugins/active_directory/RemoveIrrelevantGroupsTest.java
Adapts to jenkinsci/plugin-pom#442.
> Remove PowerMock

- src/main/resources/hudson/plugins/active_directory/Security1389AdministrativeMonitor/message.jelly
- src/main/resources/hudson/plugins/active_directory/Security1389AdministrativeMonitorLegacySysProp/message.jelly
Adopts https://github.com/jenkinsci/jenkins/pull/7364
cc @jenkinsci/active-directory-plugin-developers I'd appreciate it, if you could cut a release afterwards :)
> Forward compatibility with jenkins-buttons

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryAuthenticationProvider.java
- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
[JENKINS-69115](https://issues.jenkins.io/browse/JENKINS-69115)
> [JENKINS-69115] fire authenticated event for SecurityListeners

- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
Fix for https://issues.jenkins.io/browse/JENKINS-63303
> [JENKINS-63303] Use tokenGroups lookup strategy by default

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryDomain.java
- src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
Fix for https://issues.jenkins.io/browse/JENKINS-69683
> [JENKINS-69683] Active directory `Test Domain` does not take into account changes in the `Require TLS` checkbox

- .mvn/extensions.xml
- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
- src/test/java/hudson/plugins/active_directory/ActiveDirectoryJCasCCompatibilityTest.java
- src/test/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealmTest.java
- src/test/java/hudson/plugins/active_directory/WindowsAdsiModeUserCacheDisabledIT.java
- src/test/java/hudson/plugins/active_directory/WindowsAdsiModeUserCacheEnabledIT.java
- src/test/java/hudson/plugins/active_directory/docker/EntoEndUserCacheLookupDisabledTest.java
- src/test/java/hudson/plugins/active_directory/docker/EntoEndUserCacheLookupEnabledTest.java
- src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
Closes #169. See #168 for an explanation of the changes.
```[tasklist]
```
> Refresh plugin for June 2023

- src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
This is a small change to logging, to help troubleshoot issues. As such, the change was seen in the Jenkins logs since we started to use this patch in a custom fork.
```[tasklist]
```
> ActiveDirectoryUnixAuthenticationProvider: log the username we complain about

- src/main/resources/hudson/plugins/active_directory/ActiveDirectoryStatus/index.jelly
There was some js code in the health status jelly page that was depending on the,  no longer provided by jenkins core,  prototype.js framework.
This change replaces the prototype usage with native js code that should work without issues with more modern jenkins versions.
See https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/
I have been unable to set a proper testing environment instead I have been using the js console and tools in chrome to do the tests.
So I Modified the existing script to include two new functions that I can call at will doing the same as the existing one (adding a new file to the status table). One uses prototype exactly like the existing code and the other uses the code changes included in this pr.
```             function display(r) { …
```
> Remove prototype.js dependency

- Jenkinsfile
https://github.com/jenkinsci/active-directory-plugin/pull/83#issuecomment-1314035127 finally causing issues https://github.com/jenkins-infra/helpdesk/issues/4194
> Suppress Dockerized ITs since setup is broken

- .github/renovate.json
Amends #213 to allow updates to `src/test/resources`.
> Update `Dockerfile` used in tests with Renovate

- src/test/java/hudson/plugins/active_directory/ActiveDirectoryJCasCCompatibilityFIPSModeShortPasswordTest.java
Migrate from deprecated functionality to non-deprecated equivalents.
`mvn clean verify`
> Clean up `ActiveDirectoryJCasCCompatibilityFIPSModeShortPasswordTest`

- src/main/java/hudson/plugins/active_directory/CacheUtil.java
This PR switches the implementation of `BCrypt` used for the cache keys from jbcrypt to spring-security. I'm currently looking into removing the former library from core, and this is the only plugin using it.
Spring Security recently (Jenkins 2.502+) started rejecting passwords longer than 72 bytes, so this adds a bit of code to ensure we're not bumping into this limit.
This code is untested as the autotests did not manage to start containers (IIUC) on my system and I have no AD environment to test with. Happy to assist though if needed.
To test this, use passwords that are 71 (shorter than limit), 72 (exact limit), and 73+ bytes UTF-8 (~basic ASCII characters, or just ca. 18 emojis) long and expect the behavior to be as follows (unchanged from before), both on Jenkins before 2.502 and …
> Switch to Spring Security implementation of BCrypt
