jenkinsci/active-directory-plugin

src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
Fixing this open bug https://issues.jenkins-ci.org/browse/JENKINS-29280
I could not find a simple Jelly solution to set the autocomplete attributes. Instead using a JS workaround to attach the autocomplete attribute after the page is loaded.
=> Fixing open issue JENKINS-29280 which autofills passwords

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
The following stacktrace seems to produce active directory plugin not to fallback into recursive strategy.
```
Feb 23, 2016 9:31:54 AM hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider retrieveUser
WARNING: Failed to retrieve user information for xxxx
javax.naming.TimeLimitExceededException: [LDAP: error code 3 - Timelimit Exceeded]; remaining name 'DC=xxx,DC=xx,DC=company,DC=com'
at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3143)
at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3033)
at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2840)
at com.sun.jndi.ldap.LdapNamingEnumeration.getNextBatch(LdapNamingEnumeration.java:147)
at com.sun.jndi.ldap.LdapNamingEnumeration.hasMoreImpl(LdapNamingEnumeration.java:216)
at …
```
=> [FIXED JENKINS-33213] TimeLimitExceededException produces "Automatic" group lookup strategy not to work correctly

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
Whenever multiple domain controllers are defined, but they don't have a port assigned, only the last domain controller was given a port -> Added support for multiple servers without assigned ports.
=> Added support for multiple servers without assigned ports

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
Whenever someone tries to login with upn (someone@domain.com) the domain was appended to the username, this is unnecessary because the domain is already included in the upn.
=> [FIXED JENKINS-26737] AD can not log on with email address

src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/help-removeIrrelevantGroups.html
=> Update help for irrelevantGroups

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/resources/hudson/plugins/active_directory/Messages.properties
When testing the AD connection details you need to actually do a search to make sure the credential is valid.
https://github.com/jenkinsci/active-directory-plugin/blob/master/src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java#L392
If in this search there are not elements, we are returning null.
https://github.com/jenkinsci/active-directory-plugin/blob/master/src/main/java/hudson/plugins/active_directory/LDAPSearchBuilder.java#L98
And in this case we are saying that everything is success.
https://github.com/jenkinsci/active-directory-plugin/blob/master/src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java#L425
it might happen that under AD replication farm one of the AD instances is broken not returning any user in the search. In this …
=> [FIXED JENKINS-34143] Test Active Directory connection button reports success if the search operation doesn't have any result

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
In case in the root tree there are only OU and any USER, then the ad test button will report this. It is better to use a subtree scope so we actually look inside OUs.
https://issues.jenkins-ci.org/browse/JENKINS-34444
@reviewbybees CC @jtnord
=> [FIXED JENKINS-34444] Test button is reporting managerDN binding is successful but was not able to find any user on the tree

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUserDetail.java
```
Failed to retrieve user <user>
hudson.plugins.active_directory.CacheAuthenticationException: Authentication failed because there was a problem caching user <user>; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recursive load
at hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:340)
at hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:199)
at hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:141)
at org.acegisecurity.providers.dao.AbstractUserDetailsAuthenticationProvide …
```
=> [JENKINS-34426] Fix to handle SECURITY-243

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java, src/main/java/hudson/plugins/active_directory/GroupLookupStrategy.java, src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/help-groupLookupStrategy.html, src/main/resources/hudson/plugins/active_directory/Messages.properties
If the AD setup only requires Security Groups then we already have these
from the token-groups attribute, so searching memberOf will just make
login take longer.
The exception to this is if you have users are members of a security group
via way of a intermediate distribution group, but for these cases you can
still choose one of the other 2 methods.
@reviewbybees 
[JENKINS-36248](https://issues.jenkins-ci.org/browse/JENKINS-36248)
=> [JENKINS-36248] Provide an ultimate speed option.

src/main/java/hudson/plugins/active_directory/CacheConfiguration.java
When you configure the AD plugin (1.47) with a cache the main jenkins config contains the internals of the cache implementation and not the specific cache configuration.
```
<securityRealm class="hudson.plugins.active_directory.ActiveDirectorySecurityRealm" plugin="active-directory@1.47">
<domain>internal.local</domain>
<bindName>binduser</bindName>
<bindPassword>somevalue</bindPassword>
<server>someServer:3268</server>
<groupLookupStrategy>RECURSIVE</groupLookupStrategy>
<removeIrrelevantGroups>false</removeIrrelevantGroups>
<cache>
<size>256</size>
<ttl>30</ttl>
<userCache class="com.google.common.cache.LocalCache$LocalManualCache" resolves-to="com.google.common.cache.LocalCache$ManualSerializationProxy">
<keyStrength>STRONG</keyStrength>
<valueStrength>STRONG</valueStrength> …
```
=> [JENKINS-36212] Not serialize userCache, neither groupCache

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
This PR allows to use multiple domain controllers - even with multiple domains.
@jtnord @andresrc
=> [FIXED JENKINS-32033] Support for multiple domain controllers

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
System Property to ignore Referrals from the plugin itself.
=> JENKINS-38290 System Property to be able to ignore referrals

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
Jenkins cannot be initialized in case the descriptor of the AD plugin is saved without any domain
```
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'activeDirectory': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: An Active Directory domain name is required but it is not set
at hudson.WebAppMain$3.run(WebAppMain.java:234)
Caused by: org.jvnet.hudson.reactor.ReactorException: …
```
=> [FIXED JENKINS-40599] Not throw any Exception in case there is not any domain configured in the descriptor

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
We need to build the threadPoolExecutor on ActiveDirectoryUnixAuthenticationProvider.java - as we are doing with the cache.
=> [FIXED JENKINS-38784] Build the threadPoolExecutor in the right place

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
Enable `com.sun.jndi.ldap.connect.timeout` - the reason why it was not enabled before is that I thought it was failing for a JDK issue, but the real issue was that the plugin was injecting `TrustAllSocketFactory` even under plain communication - this was also making startTLS not to work.
=> [FIXED JENKINS-36041 JENKINS-25269] Enable com.sun.jndi.ldap.connect.timeout

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
This line of code
https://github.com/jenkinsci/active-directory-plugin/blob/active-directory-2.0/src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java#L339
should be at very least
```
new LDAPSearchBuilder(test, domainDN).subTreeScope().searchOne("(& (userPrincipalName={0})(objectCategory=user))", userPrincipalName);
```
with the subTreeScope to be able to find the user!
https://issues.jenkins-ci.org/browse/JENKINS-42462
=> [FIXED JENKINS-42462] Use subTreeScope when double checking the validity of the user

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
I thought that `JENKINS-42462` was really an issue, but thinking more about it I think that on the last step of retrieving an user where you do
```
// Binding alone is not enough to test the credential. Need to actually perform some query operation.
// but if the authentication fails this throws an exception
try {
new LDAPSearchBuilder(test, domainDN).searchOne("(& (userPrincipalName={0})(objectCategory=user))", userPrincipalName);
} finally {
closeQuietly(test);
}
```
subTreeScope() should be there as the important thing is not to even find the user, but just ensure that when launching the query we are not getting any exception.
Adding subTreeScope() could also have an important performance impact, so I prefer to be conservative.
=> [FIXED JENKINS-42462] Not have subTreeScope on the latest lookup

src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
Please @reviewbybees @fbelzunc 
Just and easy change:
<f:checkbox checked="true" />
by 
<f:checkbox default="true" />
=> [FIXED JENKINS-42831] Enable StartTls is always TRUE in the UI

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
https://issues.jenkins-ci.org/browse/JENKINS-43091
=> [JENKINS-43091] Guice failing on terminating ActiveDirectorySecurityRealm.shutDownthreadPoolExecutors

src/main/java/hudson/plugins/active_directory/ActiveDirectoryDomain.java
After updating to the active directory plugin version 2.5 the validity domain test button is incorrectly reporting that the domain is not valid. This is a regression from the previous version 2.4.
The bug was introduced in the commit https://github.com/jenkinsci/active-directory-plugin/commit/4e46466#diff-89b7b6ee37e6be852370249c03e7ca8cR283.  It's checking for not null and reporting an error when it should do the opposite.
https://issues.jenkins-ci.org/browse/JENKINS-45009
=> [FIXED JENKINS-45009] If getRecordFromDomain returns null report the problem

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java
This fixes a bug where the ActiveDirectorySecurityRealm constructor always selects `TlsConfiguration.TRUST_ALL_CERTIFICATES`, regardless of what the caller passes in. 
ActiveDirectorySecurityRealm now honors passed in TlsConfiguration making it possible to programmatically select "JDK TrustStore" when creating an ActiveDirectorySecurityRealm.
=> [FIXED JENKINS-45816] Fix ActiveDirectorySecurityRealm constructor ignoring passed in TlsConfiguration

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java, src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java, src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/custom.sh
Allowing search groups by `sAMAccount` will continue causing issues because Jenkins is considering the same AD group as two different (the one resolved by `cn` and the other by `sAMAccount`).
This PR tries to workaround the problem, not allowing search a group by `sAMAccount` and prints a log message highlighting it.
I've also added a couple of tests
=> [FIXED JENKINS-45576] AD recognizes groups by CN and sAMAccount when authorities only works with CN

src/main/java/hudson/plugins/active_directory/ActiveDirectoryDomain.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
This is not an issue on the plugin side but in the server. Added a warning message in case you leave blank the "Bind DN" field
=> [FIXED JENKINS-47133] Anonymous binding doesn't retrieve the user groups

pom.xml, src/main/java/hudson/plugins/active_directory/ActiveDirectoryMailAddressResolverImpl.java, src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryStatus.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUserDetail.java
A part of https://github.com/jenkinsci/configuration-as-code-plugin/issues/47
Some components use obsolete com4j, and it blows up the dependency check. I also bupbed the core requirement to 1.625.3, so now we do not need to bother about test/build environment differences. http://stats.jenkins.io/pluginversions/active-directory.html says that more than 95% of users run on newer core versions.
@reviewbybees
=> Update Plugin POM to 3.3, use 1.625.3 as a minimum core requirement

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/config.jelly, src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
1. This issue only happens for users running Jenkins on Windows Servers
2. If Specify a custom Active Directory domain name is not selected. Then, the only issue here is that we should never show up the banner since we are doing native authentication.
3. If Specify a custom Active Directory domain name is selected, then we should show the Advanced section because we are not doing native authentication and at this point, ActiveDirectoryUnixAuthenticationProvider is used instead of ActiveDirectoryAuthenticationProvider.
4. Cache should be visible on al cases
* https://issues.jenkins-ci.org/browse/JENKINS-52045
=> [FIXED JENKINS-52045] Tlsconfiguration in native auth & Advanced section in not native auth running on Windows box

src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/resources/hudson/plugins/active_directory/Messages.properties
See [JENKINS-54267](https://issues.jenkins-ci.org/browse/JENKINS-54267)
The display name for the TLS configuration administrative monitor is missing.
@reviewbybees 
@fbelzunc as maintainer of the plugin
=> [JENKINS-54267] Missing display name for administrative monitor

src/main/java/hudson/plugins/active_directory/ActiveDirectoryAuthenticationProvider.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java, src/main/java/hudson/plugins/active_directory/UserAttributesHelper.java
See [JENKINS-55813](https://issues.jenkins-ci.org/browse/JENKINS-55813).
=> [JENKINS-55813] Improve analysis of the AD attributes

pom.xml, src/test/java/hudson/plugins/active_directory/ActiveDirectoryJCasCCompatibilityTest.java, src/test/resources/hudson/plugins/active_directory/configuration-as-code.yaml
`active-directory-plugin` is compatible with CasC. That plugin has an [integration test](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/java/io/jenkins/plugins/casc/ActiveDirectoryTest.java), but it's fixed to an old version. Although I plan to update it as well, this PR intends to include a test in this same plugin so in case any change broke the compatibility, it can be fixed immediately
=> Add test for CasC compatibility

src/main/java/hudson/plugins/active_directory/ActiveDirectoryStatus.java
Appears "uncategorized" before this change.
=> Categorize AD Health Status

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
https://github.com/jenkinsci/active-directory-plugin/pull/109/ removed
the intermediary Callable and replaced it with a lambda, suppressing the
wrapping UncheckedExecutionException from guava. It means we no longer
need to check the exception cause but directly the exception itself and
let AuthenticationExceptions through.
=> Fix handling of AuthenticationException

Jenkinsfile, pom.xml, src/test/resources/fixture/Dockerfile, src/test/resources/fixture/custom-dockerd-entrypoint.sh, src/test/resources/fixture/daemon.json
There were failures in PCT runs against the upcoming 2.375.1 LTS due to out of date test dependencies.
Reproduced by `mvn test -Djenkins.version=2.375`
=> Bump jenkins baseline to 2.319.3, parent pom and needed dependencies

Jenkinsfile, pom.xml, src/main/java/hudson/plugins/active_directory/ActiveDirectoryDomain.java, src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/java/hudson/plugins/active_directory/DNSUtils.java, src/test/java/hudson/plugins/active_directory/WindowsAdsiModeUserCacheDisabledIT.java, src/test/java/hudson/plugins/active_directory/WindowsAdsiModeUserCacheEnabledIT.java, src/test/java/hudson/plugins/active_directory/docker/ActiveDirectoryGenericContainer.java, src/test/java/hudson/plugins/active_directory/docker/EntoEndUserCacheLookupDisabledTest.java, src/test/java/hudson/plugins/active_directory/docker/EntoEndUserCacheLookupEnabledTest.java, src/test/java/hudson/plugins/active_directory/docker/RequireDockerRule.java, src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesIT.java, src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java, src/test/resources/hudson/plugins/active_directory/docker/TheFlintstonesTest/TheFlintstones/Dockerfile
#148 revealed to me that all the containerized tests where using fixed ports.
Not only does that mean we can not run tests in parallel, it also meant that the docker tests would not work on windows as you can not bind to the CIFS ports (reserved for windows only).
The tests infact did not need these ports All bar 4 tests in the `FlinstonesTests` did not need the full e2e environment.
This moves the ports to be dynamic for most of the tests, leaving just tests split out of the FlintStones tests that need some fixed ports in a new class.
Additionally the *very special* Windows require a custom env so these and the split tests are in a IT profile.
Adapted the IT profile so that you can always run with `forkCount > 1` without any random tests as the ITs are run either on their own without the …
=> Switch test containers to dynamic ports for non integration tests

src/main/java/hudson/plugins/active_directory/ActiveDirectoryAuthenticationProvider.java, src/main/java/hudson/plugins/active_directory/ActiveDirectorySecurityRealm.java, src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
This PR intends to address [JENKINS-70492](https://issues.jenkins.io/browse/JENKINS-70492) by locating the SecurityListener at the highest level avoiding being triggered on internal lookup events which are not related to the real authentication, and which were producing `StackOverflowError`.
=> [JENKINS-70492] Only trigger SecurityListener on real authentication username/password

src/main/resources/hudson/plugins/active_directory/Security1389AdministrativeMonitor/message.jelly, src/main/resources/hudson/plugins/active_directory/Security1389AdministrativeMonitorLegacySysProp/message.jelly
Reverts jenkinsci/active-directory-plugin#140 because we're reverting the core PR.
=> Revert "Forward compatibility with jenkins-buttons"

src/main/java/hudson/plugins/active_directory/ActiveDirectoryMailAddressResolverImpl.java
There has been cases in the wild where the `UserDetailsService` is not the expected one and so will not necessarily return an AD instance of the `UserDetails` and throw a `ClassCastException` which is not technically harmful but a fortification of the scenario is good for logging.
```[tasklist]
```
=> [JENKINS-71667] Fortify MailAddressResolver

src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java
- This PR adapts the execution of `TheFlintstonesTest` for IPv6 testing environments
- It makes feasible to use the overrided DNS as `dns://[0:0:0:0:0:0:0:1]:32780`
- Tested via PCT under IPv4 and IPv6 environments and working as expected.
```[tasklist]
```
=> Adapt TheFlintstonesTest to IPv6 testing environments

.mvn/extensions.xml
For unknown reasons, @dependabot is not offering this. Trunk builds broken trying to accessing 1.7, also for unknown reasons.
=> Bump `git-changelist-maven-extension` to 1.8

src/main/resources/hudson/plugins/active_directory/ActiveDirectoryStatus/ad-display.js, src/main/resources/hudson/plugins/active_directory/ActiveDirectoryStatus/index.jelly
https://issues.jenkins.io/browse/JENKINS-74036
Under Manage Jenkins go to the Active Directory Health Status page. The inline script block was defining a `display` function in the global scope. I've verified that function is also available in global scope after the change. That function is passed as a callback to the `progressiveRendering` tag: https://github.com/jenkinsci/active-directory-plugin/blob/03c944f9f7e6a195d1f770666c23f285b1329836/src/main/resources/hudson/plugins/active_directory/ActiveDirectoryStatus/index.jelly#L98.
[Before the change](https://www.youtube.com/watch?v=LMFm4-ihyWI)
[After the change](https://www.youtube.com/watch?v=Qg33q-9ULt8)
=> [JENKINS-74036] Extract inline script from `ActiveDirectoryStatus/index.jelly`

src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/ad-turn-off-autocomplete.js, src/main/resources/hudson/plugins/active_directory/ActiveDirectorySecurityRealm/configAdvanced.jelly
https://issues.jenkins.io/browse/JENKINS-74035
Go to the Global Security Configuration page, select Active Directory as a security realm.
It's a bit weird that that code adds the event listener on `DOMContentLoaded`, because when changing the security realm to Active Directory that event has long been fired. So that code would only be executed when the realm is already set to Active Directory and then you're entering the Global Security Configuration page. Unsure if it's intentional or just a bug. But that behavior is preserved.
[Before the change](https://www.youtube.com/watch?v=XghQv6rED38)
[After the change](https://www.youtube.com/watch?v=JKDSA80e_Jw)
=> [JENKINS-74035] Extract inline script from `ActiveDirectorySecurityRealm/configAdvanced.jelly`

src/main/java/hudson/plugins/active_directory/ActiveDirectoryUnixAuthenticationProvider.java
Fix TODO: rethrow NamingException instead of throwing a new, blank NamingException so actual errors can be seen/investigated further
Logs exhibit following before change (for suspected failure to get all AD groups for an SSO authenticated user):
WARNING: Communications issues when trying to authenticate against ${DOMAIN} for user ${USERNAME}
java.naming.NamingException
at hudson.plugins.active_directory.ActiveDirectoryUnixAuthenticationProvider.retrieveUser(ActiveDirectoryUnixAuthenticationProvider.java:500)
This line is the `throw new` and doesn't include information about actual cause of error.
Logs exhibit following after change (for same attempted login):
WARNING: Communications issues when trying to authenticate against ${DOMAIN} for user ${USERNAME}
javax.naming.NaminException: …
=> Fix TODO and rethrow `NamingException` for root cause analysis
